### PR TITLE
Update .gitmodules to use HTTPS

### PR DESCRIPTION
**Pull request by qurious-pixel**

### CODE REVIEW

**Comment by AngheloAlf** [comment]
Hey! Thanks for your interest on this project, but I should let you know that this project isn't meant to have a public release or anything like that, this is just me having fun with the recompilation technology and finding possible issues with the rest of the tooling, so I wasn't really expecting anybody to make a PR here.

I'm curious, how did you even find this repository? I didn't expect anybody else to be interested on this game.

Also, what's the motivation of this PR? Seems like a pretty random change to do.

**Comment by qurious-pixel** [comment]
The submodules will not load when not signed into git when set as git ssh instead of https, leading to an incomplete build. 

I was following this build only as a separate example from Z64-MM to help me build my own decomp/recomp project, mainly Cruisi'n USA.

I saw that you implemented n64modernruntime, something i was also doing with this repo, but you retained all of the zelda64 namespace. I was trying to avoid using that, but your implementation works, and I was also able to build.

**Comment by theboy181** [comment]
I would hope that you would have artifacts at minimum for the plebs to play around with. Any way this could be encouraged?

**Comment by AngheloAlf** [comment]
> The submodules will not load when not signed into git when set as git ssh instead of https, leading to an incomplete build.

You need to setup your ssh keys if you plan pushing anything to github, don't you? I personally don't see the problem with setting up this. So if this somehow encourages people to actually set up the repository then I'm all in with it.

> I was following this build only as a separate example from Z64-MM to help me build my own decomp/recomp project, mainly Cruisi'n USA.

Oh, nice. I'm glad that this is helping other people. This repo doesn't really have many changes compared to the zelda one, just the bare minimum to work, so it may be better to use the Zelda one as a reference since that one is more prone to be up to date. At least until Wiseguy releases his planned minimum recomp example.

> I saw that you implemented n64modernruntime, something i was also doing with this repo, but you retained all of the zelda64 namespace. I was trying to avoid using that, but your implementation works, and I was also able to build.

Ah yeah, I kept all the changes to a minimum, mainly to make it easier to pull the latest changes from the Zelda repo. I have considered stripping all the zelda related improvements in the code, but I'm kinda ambivalent on this, since I'm not sure if that would make harder to pull changes from Zelda recomp.

**Comment by AngheloAlf** [comment]
> I would hope that you would have artifacts at minimum for the plebs to play around with. Any way this could be encouraged?

No, not really. As I said earlier, this repo is just me playing with the recomp technology, not the game itself. This means everything that I will do with the repo is meant to be used by me locally, setting up CI would be more annoying than useful to me.

The only reason why this repo is public is because something may break and I may need to give to other people that want to help me a way to build the repo locally too, otherwise this repo would be just on my pc or on a private repo.

If anybody is interested on actually playing this game (which I don't recommend, since at its current state is unplayable) then they could clone it and build it themselves, I wrote some build instructions for myself in case I forgot how to build it.

**Comment by qurious-pixel** [comment]
I will close this as unplanned. But for others who do wish to clone this locally, the steps would be to edit the `.gitmodules` file and replace the `git@:` with `https`
```
[submodule "lib/rt64"]
	path = lib/rt64
	url = https://github.com/rt64/rt64
[submodule "lib/concurrentqueue"]
	path = lib/concurrentqueue
	url = https://github.com/cameron314/concurrentqueue
[submodule "lib/GamepadMotionHelpers"]
	path = lib/GamepadMotionHelpers
	url = https://github.com/JibbSmart/GamepadMotionHelpers
[submodule "lib/RmlUi"]
	path = lib/RmlUi
	url = https://github.com/mikke89/RmlUi/
[submodule "lib/lunasvg"]
	path = lib/lunasvg
	url = https://github.com/sammycage/lunasvg
[submodule "lib/freetype-windows-binaries"]
	path = lib/freetype-windows-binaries
	url = https://github.com/ubawurinna/freetype-windows-binaries
[submodule "lib/sse2neon"]
	path = lib/sse2neon
	url = https://github.com/DLTcollab/sse2neon
[submodule "lib/N64ModernRuntime"]
	path = lib/N64ModernRuntime
	url = https://github.com/N64Recomp/N64ModernRuntime
```

Then run from the repo `git submodule sync --recursive` and then `git submodule update --init --recursive`

**Pull request closed without merging**
